name: Publish ASV Results

on:
  push:
    branches:
      - main    # Or your main development branch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Adjust as appropriate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install asv

      - name: Publish ASV HTML
        run: asv publish

      - name: Deploy to gh-pages
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages
          rm -rf *
          cp -r html/* .
          git add .
          git commit -m "Update ASV HTML [skip ci]" || echo "No changes to commit"
          git push origin gh-pages

